# analysis { #kimmdy.analysis }

`analysis`

Analysis tools for KIMMDY runs.
For command line usage, run `kimmdy-analysis -h`.

## Functions

| Name | Description |
| --- | --- |
| [concat_traj](#kimmdy.analysis.concat_traj) | Find and concatenate trajectories (.xtc files) from a KIMMDY run into one trajectory. |
| [entry_point_analysis](#kimmdy.analysis.entry_point_analysis) | Analyse existing KIMMDY runs. |
| [get_analysis_cmdline_args](#kimmdy.analysis.get_analysis_cmdline_args) | Parse command line arguments. |
| [get_analysis_dir](#kimmdy.analysis.get_analysis_dir) | Get analysis directory for a KIMMDY run. |
| [plot_energy](#kimmdy.analysis.plot_energy) | Plot GROMACS energy for a KIMMDY run. |
| [plot_rates](#kimmdy.analysis.plot_rates) | Plot rates of all possible reactions for each 'decide_recipe' step. |
| [radical_migration](#kimmdy.analysis.radical_migration) | Plot population of radicals for a KIMMDY run. |
| [radical_population](#kimmdy.analysis.radical_population) | Plot population of radicals for a KIMMDY run. |
| [reaction_participation](#kimmdy.analysis.reaction_participation) | Plot which atoms participate in reactions. |
| [runtime_analysis](#kimmdy.analysis.runtime_analysis) | Plot which atoms participate in reactions. |

### concat_traj { #kimmdy.analysis.concat_traj }

```python
analysis.concat_traj(
    dir,
    filetype,
    steps,
    open_vmd=False,
    output_group=None,
    center_group=None,
    use_last_names=False,
)
```

Find and concatenate trajectories (.xtc files) from a KIMMDY run into one trajectory.
The concatenated trajectory is centered and pbc corrected.

#### Parameters {.doc-section .doc-section-parameters}

| Name           | Type                                                                    | Description                                                                                                                                                                    | Default    |
|----------------|-------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| dir            | [str](`str`)                                                            | Directory to search for subdirectories                                                                                                                                         | _required_ |
| steps          | [Union](`typing.Union`)\[[list](`list`)\[[str](`str`)\], [str](`str`)\] | List of steps e.g. ["equilibrium", "production"]. Or a string "all" to return all subdirectories                                                                               | _required_ |
| open_vmd       | [bool](`bool`)                                                          | Open concatenated trajectory in VMD                                                                                                                                            | `False`    |
| output_group   | [Optional](`typing.Optional`)\[[str](`str`)\]                           | index group for output. Default is "Protein" for xtc and "System" for trr.                                                                                                     | `None`     |
| output_group   | [Optional](`typing.Optional`)\[[str](`str`)\]                           | index group for centering.                                                                                                                                                     | `None`     |
| use_last_names | [bool](`bool`)                                                          | Use the tpr/topology of the last trajectory for the output, default is the first. This influences the names and types of the atoms in the output, which can be useful for VMD. | `False`    |

### entry_point_analysis { #kimmdy.analysis.entry_point_analysis }

```python
analysis.entry_point_analysis()
```

Analyse existing KIMMDY runs.

### get_analysis_cmdline_args { #kimmdy.analysis.get_analysis_cmdline_args }

```python
analysis.get_analysis_cmdline_args()
```

Parse command line arguments.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                          | Description   |
|--------|-------------------------------|---------------|
|        | Parsed command line arguments |               |

### get_analysis_dir { #kimmdy.analysis.get_analysis_dir }

```python
analysis.get_analysis_dir(dir)
```

Get analysis directory for a KIMMDY run.

Creates the directory if it does not exist.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                   | Description             | Default    |
|--------|------------------------|-------------------------|------------|
| dir    | [Path](`pathlib.Path`) | Directory of KIMMDY run | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                       | Description   |
|--------|----------------------------|---------------|
|        | Path to analysis directory |               |

### plot_energy { #kimmdy.analysis.plot_energy }

```python
analysis.plot_energy(dir, steps, terms, open_plot=False, truncate=True)
```

Plot GROMACS energy for a KIMMDY run.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type                                                                    | Description                                                                                                         | Default    |
|-----------|-------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|------------|
| dir       | [str](`str`)                                                            | Directory to search for subdirectories                                                                              | _required_ |
| steps     | [Union](`typing.Union`)\[[list](`list`)\[[str](`str`)\], [str](`str`)\] | List of steps e.g. ["equilibrium", "production"]. Or a string "all" to return all subdirectories. Default is "all". | _required_ |
| terms     | [list](`list`)\[[str](`str`)\]                                          | Terms from gmx energy that will be plotted. Uses 'Potential' by default.                                            | _required_ |
| open_plot | [bool](`bool`)                                                          | Open plot in default system viewer.                                                                                 | `False`    |
| truncate  | [bool](`bool`)                                                          | Truncate energy files to the reaction time marker.                                                                  | `True`     |

### plot_rates { #kimmdy.analysis.plot_rates }

```python
analysis.plot_rates(dir, open=False)
```

Plot rates of all possible reactions for each 'decide_recipe' step.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type           | Description                         | Default    |
|--------|----------------|-------------------------------------|------------|
| dir    | [str](`str`)   | Directory of KIMMDY run             | _required_ |
| open   | [bool](`bool`) | open plots in default system viewer | `False`    |

### radical_migration { #kimmdy.analysis.radical_migration }

```python
analysis.radical_migration(dirs, type='qualitative', cutoff=1)
```

Plot population of radicals for a KIMMDY run.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                           | Description                                                                                | Default         |
|--------|--------------------------------|--------------------------------------------------------------------------------------------|-----------------|
| dirs   | [list](`list`)\[[str](`str`)\] | KIMMDY run directories to be analysed.                                                     | _required_      |
| type   | [str](`str`)                   | How to analyse radical migration. Available are 'qualitative','occurence' and 'min_rate'", | `'qualitative'` |
| cutoff | [int](`int`)                   | Ignore migration between two atoms if it happened less often than the specified value.     | `1`             |

### radical_population { #kimmdy.analysis.radical_population }

```python
analysis.radical_population(
    dir,
    population_type='frequency',
    steps='all',
    select_atoms='protein',
    open_plot=False,
    open_vmd=False,
)
```

Plot population of radicals for a KIMMDY run.

#### Parameters {.doc-section .doc-section-parameters}

| Name            | Type                                                                    | Description                                                                                                         | Default       |
|-----------------|-------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|---------------|
| dir             | [str](`str`)                                                            | KIMMDY run directory to be analysed.                                                                                | _required_    |
| population_type | [str](`str`)                                                            | How to calculate the fractional radical occupancy. Available are 'frequency' and 'time'                             | `'frequency'` |
| steps           | [Union](`typing.Union`)\[[list](`list`)\[[str](`str`)\], [str](`str`)\] | List of steps e.g. ["equilibrium", "production"]. Or a string "all" to return all subdirectories. Default is "all". | `'all'`       |
| select_atoms    | [str](`str`)                                                            | Atoms chosen for radical population analysis, default is protein (uses MDAnalysis selection syntax)                 | `'protein'`   |
| open_plot       | [bool](`bool`)                                                          | Open plot in default system viewer.                                                                                 | `False`       |
| open_vmd        | [bool](`bool`)                                                          | Open a pdb in VMD with the radical occupation as B-factors.                                                         | `False`       |

### reaction_participation { #kimmdy.analysis.reaction_participation }

```python
analysis.reaction_participation(dir, open_plot=False)
```

Plot which atoms participate in reactions.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type           | Description                         | Default    |
|-----------|----------------|-------------------------------------|------------|
| dir       | [str](`str`)   | Directory of KIMMDY run             | _required_ |
| open_plot | [bool](`bool`) | Open plot in default system viewer. | `False`    |

### runtime_analysis { #kimmdy.analysis.runtime_analysis }

```python
analysis.runtime_analysis(dir, open_plot=False)
```

Plot which atoms participate in reactions.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type           | Description                         | Default    |
|-----------|----------------|-------------------------------------|------------|
| dir       | [str](`str`)   | Directory of KIMMDY run             | _required_ |
| open_plot | [bool](`bool`) | Open plot in default system viewer. | `False`    |