# changemanager { #kimmdy.changemanager }

`changemanager`

The changemanager module holds functions that modify the system
to accomodate recipes.
This includes the topolgy and coordinates as well miscelaneaous files
used by e.g. the gromacs extension PLUMED as input. 

TODO: some functions in here take TaskFiles, some take their inputs
directly. Need to unify.

## Functions

| Name | Description |
| --- | --- |
| [break_bond_plumed](#kimmdy.changemanager.break_bond_plumed) |  |
| [modify_coords](#kimmdy.changemanager.modify_coords) | Modify the coordinates of the system according to the recipe steps. |
| [modify_plumed](#kimmdy.changemanager.modify_plumed) | Modify plumed input files. |
| [modify_top](#kimmdy.changemanager.modify_top) | Modify the topology of the system according to the recipe steps. |

### break_bond_plumed { #kimmdy.changemanager.break_bond_plumed }

`changemanager.break_bond_plumed(plumeddat, breakpair, plumeddist)`

### modify_coords { #kimmdy.changemanager.modify_coords }

`changemanager.modify_coords(recipe_steps, files, topA, topB)`

Modify the coordinates of the system according to the recipe steps.

New coordinates are generated by merging topA and topB and interpolating
between them in a MD simulation.

TODO: the previous sentence is a lie right now, the MD step happens
in a different function as its own task, so
this function does not actually modify any coordinates,
contrary to its name.
We should either change the name or make it do what it says it does.

#### Parameters

| Name           | Type                               | Description                                                                                                                  | Default    |
|----------------|------------------------------------|------------------------------------------------------------------------------------------------------------------------------|------------|
| `recipe_steps` | list\[kimmdy.reaction.RecipeStep\] | A list of [](`~kimmdy.tasks.Task`) [](`~kimmdy.reaction.RecipeStep`) where each steps contains a `new_coords` parameter.     | _required_ |
| `files`        | TaskFiles                          | Input and output files for this [](`~kimmdy.tasks.Task`). files.input: - trr - tpr files.outputdir files.output: - trr - gro | _required_ |
| `topA`         | Topology                           | Previous Topology                                                                                                            | _required_ |
| `topB`         | Topology                           | Parameter-adjusted Topology                                                                                                  | _required_ |

### modify_plumed { #kimmdy.changemanager.modify_plumed }

`changemanager.modify_plumed(recipe_steps, oldplumeddat, newplumeddat, plumeddist)`

Modify plumed input files.

TODO: finish this function.

#### Parameters

| Name           | Type                               | Description                                                        | Default    |
|----------------|------------------------------------|--------------------------------------------------------------------|------------|
| `recipe_steps` | list\[kimmdy.reaction.RecipeStep\] | A list of [RecipeStep](`~kimmdy.reaction.RecipeStep`)s. parameter. | _required_ |

### modify_top { #kimmdy.changemanager.modify_top }

`changemanager.modify_top(recipe_steps, files, ffpatch, topology)`

Modify the topology of the system according to the recipe steps.

Modifies the topology in place and also writes the new topology
to a file to be used by external programs (gromacs).

#### Parameters

| Name           | Type                                                 | Description                                                                                           | Default    |
|----------------|------------------------------------------------------|-------------------------------------------------------------------------------------------------------|------------|
| `recipe_steps` | list\[kimmdy.reaction.RecipeStep\]                   | A list of [RecipeStep](``kimmdy.reaction.RecipeStep``)s. parameter.                                   | _required_ |
| `files`        | TaskFiles                                            | Input and output files for this [Task](``kimmdy.tasks.Task``). files.input: - top files.output: - top | _required_ |
| `ffpatch`      | typing.Optional\[pathlib.Path\]                      | TODO: deprecate                                                                                       | _required_ |
| `topology`     | typing.Optional\[kimmdy.topology.topology.Topology\] | TODO: make this required instead of optional                                                          | _required_ |