# Reference

## API

Start KIMMDY from a python script or the command line

| | |
| --- | --- |
| [cmd](cmd.qmd#kimmdy.cmd) | Functions for starting KIMMDY either from python or the command line. |

## Topology

Topology modules

| | |
| --- | --- |
| [topology.topology](topology.topology.qmd#kimmdy.topology.topology) |  |
| [topology.ff](topology.ff.qmd#kimmdy.topology.ff) |  |
| [topology.utils](topology.utils.qmd#kimmdy.topology.utils) |  |
| [topology.atomic](topology.atomic.qmd#kimmdy.topology.atomic) | Atomic datatypes for the topology such as Atom, Bond, Angle, Dihedral, etc. |
| [parsing.TopologyDict](parsing.TopologyDict.qmd#kimmdy.parsing.TopologyDict) | A raw representation of a topology file returned by [](`~kimmdy.parsing.read_top`). |

## Modules

Modules

| | |
| --- | --- |
| [analysis](analysis.qmd#kimmdy.analysis) | Analysis tools for KIMMDY runs. |
| [cmd](cmd.qmd#kimmdy.cmd) | Functions for starting KIMMDY either from python or the command line. |
| [config](config.qmd#kimmdy.config) | Read and validate kimmdy.yml configuration files |
| [constants](constants.qmd#kimmdy.constants) | Comstants used throughout KIMMDY |
| [coordinates](coordinates.qmd#kimmdy.coordinates) | coordinate, topology and plumed modification functions |
| [kmc](kmc.qmd#kimmdy.kmc) | Kinetic Monte Carlo (KMC) classes and functions. |
| [parsing](parsing.qmd#kimmdy.parsing) | All read_<...> and write_<...> functions. |
| [plugins](plugins.qmd#kimmdy.plugins) | Plugin base classes and basic instances thereof. |
| [recipe](recipe.qmd#kimmdy.recipe) | Contains the Reaction Recipe, RecipeStep and RecipeCollection. |
| [runmanager](runmanager.qmd#kimmdy.runmanager) | The Runmanager is the main entry point of the program. |
| [schema](schema.qmd#kimmdy.schema) | Handle the schema for the config file. |
| [tasks](tasks.qmd#kimmdy.tasks) | The tasks module holds the TaskFiles class which organizes input and  |
| [tools](tools.qmd#kimmdy.tools) | Standalone tools that are complementary to KIMMDY. |
| [utils](utils.qmd#kimmdy.utils) | Utilities for building plugins, shell convenience functions and GROMACS related functions |

## Reaction Plugins

Reaction plugins bundled with KIMMDY and the protocol to add a new reaction plugin to KIMMDY

| | |
| --- | --- |
| [homolysis.reaction.Homolysis](homolysis.reaction.Homolysis.qmd#homolysis.reaction.Homolysis) | Homolytic bond breaking leading to 2 radicals. |
| [hat_naive.reaction.NaiveHAT](hat_naive.reaction.NaiveHAT.qmd#hat_naive.reaction.NaiveHAT) | Naive HAT reaction, selects hydrogens at random |
| [dummyreaction.reaction.DummyReaction](dummyreaction.reaction.DummyReaction.qmd#dummyreaction.reaction.DummyReaction) | Dummy reaction, returns empty RecipeCollection |