# misc_helper { #kimmdy.misc_helper }

`misc_helper`

Miscelaneous utilitiies that didn&#x27;t fit anywhere else for now.

## Functions

| Name | Description |
| --- | --- |
| [concat_traj](#kimmdy.misc_helper.concat_traj) | Find and concatenate trajectories from KIMMDY runs. |
| [edgelist_to_dot_graph](#kimmdy.misc_helper.edgelist_to_dot_graph) |  |
| [top_to_graph](#kimmdy.misc_helper.top_to_graph) |  |
| [topology_to_edgelist](#kimmdy.misc_helper.topology_to_edgelist) |  |

### concat_traj { #kimmdy.misc_helper.concat_traj }

`misc_helper.concat_traj(run_dir, out=None, run_types=None)`

Find and concatenate trajectories from KIMMDY runs.

#### Parameters

| Name        | Type                                   | Description                                                                                       | Default    |
|-------------|----------------------------------------|---------------------------------------------------------------------------------------------------|------------|
| `run_dir`   | [Path](`pathlib.Path`) \| [str](`str`) | Directory containing directories of multiple tasks.                                               | _required_ |
| `out`       | [Path](`pathlib.Path`)                 | File Path into the output trr will be written. Default `concat.trr` in given run_dir              | `None`     |
| `run_types` | [list](`list`)                         | List of tasks to get trrs from. If a task is not in this list it will be skipped. By default None | `None`     |

### edgelist_to_dot_graph { #kimmdy.misc_helper.edgelist_to_dot_graph }

`misc_helper.edgelist_to_dot_graph(ls, overlap='true')`

### top_to_graph { #kimmdy.misc_helper.top_to_graph }

`misc_helper.top_to_graph(top, overlap='true')`

### topology_to_edgelist { #kimmdy.misc_helper.topology_to_edgelist }

`misc_helper.topology_to_edgelist(top)`