# reaction { #kimmdy.reaction }

`reaction`

ReactionPlugin protocoll and reaction recipes.

## Classes

| Name | Description |
| --- | --- |
| [Bind](#kimmdy.reaction.Bind) | Change topology to form a bond |
| [Break](#kimmdy.reaction.Break) | Change topology to break a bond |
| [Move](#kimmdy.reaction.Move) | Change topology and/or coordinates to move an atom. |
| [ReactionPlugin](#kimmdy.reaction.ReactionPlugin) | Reaction base class |
| [Recipe](#kimmdy.reaction.Recipe) | A reaction path defined by one series of RecipeSteps. |
| [RecipeCollection](#kimmdy.reaction.RecipeCollection) | A RecipeCollection encompasses a number of reaction paths. |
| [RecipeStep](#kimmdy.reaction.RecipeStep) | Base class for all RecipeSteps. |
| [SingleOperation](#kimmdy.reaction.SingleOperation) | Handle a single operation on the recipe step. |

### Bind { #kimmdy.reaction.Bind }

`reaction.Bind()`

Change topology to form a bond

#### Parameters

| Name        | Type         | Description                                               | Default    |
|-------------|--------------|-----------------------------------------------------------|------------|
| `atom_ix_1` | [int](`int`) | The index of the first atom. zero-based, by default None  | _required_ |
| `atom_ix_2` | [int](`int`) | The index of the second atom. zero-based, by default None | _required_ |
| `atom_id_1` | [str](`str`) | The ID of the first atom. one-based, by default None      | _required_ |
| `atom_id_2` | [str](`str`) | The ID of the second atom. one-based, by default None     | _required_ |

### Break { #kimmdy.reaction.Break }

`reaction.Break()`

Change topology to break a bond

#### Parameters

| Name        | Type         | Description                                               | Default    |
|-------------|--------------|-----------------------------------------------------------|------------|
| `atom_ix_1` | [int](`int`) | The index of the first atom. zero-based, by default None  | _required_ |
| `atom_ix_2` | [int](`int`) | The index of the second atom. zero-based, by default None | _required_ |
| `atom_id_1` | [str](`str`) | The ID of the first atom. one-based, by default None      | _required_ |
| `atom_id_2` | [str](`str`) | The ID of the second atom. one-based, by default None     | _required_ |

### Move { #kimmdy.reaction.Move }

`reaction.Move(ix_to_move, ix_to_bind, ix_to_break, new_coords=None, id_to_move, id_to_bind, id_to_break, _ix_to_move=field(init=False, repr=False, default=None), _ix_to_bind=field(init=False, repr=False, default=None), _ix_to_break=field(init=False, repr=False, default=None))`

Change topology and/or coordinates to move an atom.

#### Parameters

| Name          | Type                                                                                                                                            | Description                                                                                   | Default    |
|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|------------|
| `ix_to_move`  | [int](`int`)                                                                                                                                    | Index of atom to move. 0-based.                                                               | _required_ |
| `ix_to_bind`  | [int](`int`)                                                                                                                                    | Bonding partner to form bond with. 0-based.                                                   | _required_ |
| `ix_to_break` | [int](`int`)                                                                                                                                    | Bonding partner to break bond with, default None. 0-based.                                    | _required_ |
| `new_coords`  | [Optional](`typing.Optional`)\[[tuple](`tuple`)\[[tuple](`tuple`)\[[float](`float`), [float](`float`), [float](`float`)\], [float](`float`)\]\] | Optional new xyz coordinates for atom to move to, and the associated time in ps default None. | `None`     |
| `id_to_move`  | [str](`str`)                                                                                                                                    | Index of atom to move. 1-based                                                                | _required_ |
| `id_to_bind`  | [str](`str`)                                                                                                                                    | Bonding partner to form bond with. 1-based                                                    | _required_ |
| `id_to_break` | [str](`str`)                                                                                                                                    | Bonding partner to break bond with, default None. 1-based                                     | _required_ |

### ReactionPlugin { #kimmdy.reaction.ReactionPlugin }

`reaction.ReactionPlugin(self, name, runmng)`

Reaction base class

#### Parameters

| Name     | Type                                         | Description          | Default    |
|----------|----------------------------------------------|----------------------|------------|
| `name`   | [str](`str`)                                 | Name of the reaction | _required_ |
| `runmng` | [RunManager](`kimmdy.runmanager.RunManager`) | RunManager instance  | _required_ |

#### Methods

| Name | Description |
| --- | --- |
| [get_recipe_collection](#kimmdy.reaction.ReactionPlugin.get_recipe_collection) | Get a RecipeCollection as a result of the reaction. |

##### get_recipe_collection { #kimmdy.reaction.ReactionPlugin.get_recipe_collection }

`reaction.ReactionPlugin.get_recipe_collection(self, files)`

Get a RecipeCollection as a result of the reaction.

This is run as a [](`~kimmdy.tasks.Task`) in the RunManager.
How the RecipeCollection is built is up to the reaction.
It has access to the current state of the system via the
runmanager `self.runmng` and the files.

###### Parameters

| Name    | Type                                  | Description        | Default    |
|---------|---------------------------------------|--------------------|------------|
| `files` | [TaskFiles](`kimmdy.tasks.TaskFiles`) | TaskFiles instance | _required_ |

### Recipe { #kimmdy.reaction.Recipe }

`reaction.Recipe(recipe_steps, rates, timespans)`

A reaction path defined by one series of RecipeSteps.
Defines everything necessart to build the
product state from the educt state.

#### Parameters

| Name           | Type                                                                   | Description                                                                                                                                                        | Default    |
|----------------|------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `recipe_steps` | [list](`list`)\[[RecipeStep](`kimmdy.reaction.RecipeStep`)\]           | Single sequence of RecipeSteps to build product                                                                                                                    | _required_ |
| `rates`        | [list](`list`)\[[float](`float`)\]                                     | Reaction rates corresponding 1:1 to timespans.                                                                                                                     | _required_ |
| `timespans`    | [list](`list`)\[[list](`list`)\[[float](`float`), [float](`float`)\]\] | List of half-open timespans (t1, t2] in ps, at which this reaction path applies. Must have same number of timespans as rates. t1 can equal t2 for the first frame. | _required_ |

#### Methods

| Name | Description |
| --- | --- |
| [calc_averages](#kimmdy.reaction.Recipe.calc_averages) | Calulate average rates over some window size |
| [check_consistency](#kimmdy.reaction.Recipe.check_consistency) | Run consistency checks for correct size of variables |
| [combine_with](#kimmdy.reaction.Recipe.combine_with) | Combines this Recipe with another with the same RecipeSteps. |

##### calc_averages { #kimmdy.reaction.Recipe.calc_averages }

`reaction.Recipe.calc_averages(self, window_size)`

Calulate average rates over some window size

###### Parameters

| Name          | Type         | Description                                                                   | Default    |
|---------------|--------------|-------------------------------------------------------------------------------|------------|
| `window_size` | [int](`int`) | Size of the window to average over, -1 to average over whole available range. | _required_ |

##### check_consistency { #kimmdy.reaction.Recipe.check_consistency }

`reaction.Recipe.check_consistency(self)`

Run consistency checks for correct size of variables

##### combine_with { #kimmdy.reaction.Recipe.combine_with }

`reaction.Recipe.combine_with(self, other)`

Combines this Recipe with another with the same RecipeSteps.

###### Parameters

| Name    | Type                               | Description   | Default    |
|---------|------------------------------------|---------------|------------|
| `other` | [Recipe](`kimmdy.reaction.Recipe`) |               | _required_ |

### RecipeCollection { #kimmdy.reaction.RecipeCollection }

`reaction.RecipeCollection(recipes)`

A RecipeCollection encompasses a number of reaction paths.
They can originate from multiple reaction plugins, but do not need to.

#### Methods

| Name | Description |
| --- | --- |
| [aggregate_reactions](#kimmdy.reaction.RecipeCollection.aggregate_reactions) | Combines reactions having the same sequence of RecipeSteps. |
| [to_csv](#kimmdy.reaction.RecipeCollection.to_csv) | Write a ReactionResult as defined in the reaction module to a csv file |

##### aggregate_reactions { #kimmdy.reaction.RecipeCollection.aggregate_reactions }

`reaction.RecipeCollection.aggregate_reactions(self)`

Combines reactions having the same sequence of RecipeSteps.

##### to_csv { #kimmdy.reaction.RecipeCollection.to_csv }

`reaction.RecipeCollection.to_csv(self, path)`

Write a ReactionResult as defined in the reaction module to a csv file

### RecipeStep { #kimmdy.reaction.RecipeStep }

`reaction.RecipeStep()`

Base class for all RecipeSteps.
Indices can be accessed as 0-based or 1-based.
ix: 0-based, int
id: 1-based, str

### SingleOperation { #kimmdy.reaction.SingleOperation }

`reaction.SingleOperation(atom_ix_1, atom_ix_2, atom_id_1, atom_id_2, _atom_ix_1=field(init=False, repr=False, default=None), _atom_ix_2=field(init=False, repr=False, default=None))`

Handle a single operation on the recipe step.

This class takes in either zero-based indices or one-base IDs for two atoms

#### Parameters

| Name        | Type         | Description                                               | Default    |
|-------------|--------------|-----------------------------------------------------------|------------|
| `atom_ix_1` | [int](`int`) | The index of the first atom. zero-based, by default None  | _required_ |
| `atom_ix_2` | [int](`int`) | The index of the second atom. zero-based, by default None | _required_ |
| `atom_id_1` | [str](`str`) | The ID of the first atom. one-based, by default None      | _required_ |
| `atom_id_2` | [str](`str`) | The ID of the second atom. one-based, by default None     | _required_ |

#### Raises

| Type                       | Description                                                     |
|----------------------------|-----------------------------------------------------------------|
| [ValueError](`ValueError`) | If neither an index nor an ID is provided for any of the atoms. |

#### Notes

Internally, this class stores the atom indices and converts IDs to indices as needed.