# cmd { #kimmdy.cmd }

`cmd`

## Functions

| Name | Description |
| --- | --- |
| [configure_logging](#kimmdy.cmd.configure_logging) | Configure logging. |
| [get_cmdline_args](#kimmdy.cmd.get_cmdline_args) | Parse command line arguments and configure logger. |
| [kimmdy](#kimmdy.cmd.kimmdy) | Run KIMMDY from the command line. |
| [kimmdy_run](#kimmdy.cmd.kimmdy_run) | Run KIMMDY from python. |

## configure_logging { #kimmdy.cmd.configure_logging }

`cmd.configure_logging(args, color=False)`

Configure logging.

Configures the logging module with optional colorcodes
for the terminal.

## get_cmdline_args { #kimmdy.cmd.get_cmdline_args }

`cmd.get_cmdline_args()`

Parse command line arguments and configure logger.

### Returns

| Type      | Description                   |
|-----------|-------------------------------|
| Namespace | parsed command line arguments |

## kimmdy { #kimmdy.cmd.kimmdy }

`cmd.kimmdy()`

Run KIMMDY from the command line.

The configuration is gathered from the input file,
which is `kimmdy.yml` by default.

## kimmdy_run { #kimmdy.cmd.kimmdy_run }

`cmd.kimmdy_run(input=Path('kimmdy.yml'), loglevel='DEBUG', logfile=Path('kimmdy.log'))`

Run KIMMDY from python.