# coordinates { #kimmdy.coordinates }

`coordinates`

TODO: WIP

## Functions

| Name | Description |
| --- | --- |
| [get_atomicobj](#kimmdy.coordinates.get_atomicobj) |  |
| [get_keys](#kimmdy.coordinates.get_keys) |  |
| [is_parameterized](#kimmdy.coordinates.is_parameterized) | Parameterized topology entries have c0 and c1 attributes != None |
| [merge_same](#kimmdy.coordinates.merge_same) |  |
| [merge_top_parameter_growth](#kimmdy.coordinates.merge_top_parameter_growth) |  |

### get_atomicobj { #kimmdy.coordinates.get_atomicobj }

`coordinates.get_atomicobj(key, type, top)`

### get_keys { #kimmdy.coordinates.get_keys }

`coordinates.get_keys(atomicA, atomicB)`

### is_parameterized { #kimmdy.coordinates.is_parameterized }

`coordinates.is_parameterized(entry)`

Parameterized topology entries have c0 and c1 attributes != None

### merge_same { #kimmdy.coordinates.merge_same }

`coordinates.merge_same(same, topA, topB, type)`

### merge_top_parameter_growth { #kimmdy.coordinates.merge_top_parameter_growth }

`coordinates.merge_top_parameter_growth(topA, topB, focus_nr=None)`