# Function reference

## API

Start KIMMDY from a python script or the command line

| | |
| --- | --- |
| [cmd](cmd.qmd#kimmdy.cmd) | Functions for starting KIMMDY either from python or the command line. |

## Modules

Modules

| | |
| --- | --- |
| [changemanager](changemanager.qmd#kimmdy.changemanager) | The changemanager module holds functions that modify the system |
| [config](config.qmd#kimmdy.config) | Read and validate kimmdy.yml configuration files |
| [constants](constants.qmd#kimmdy.constants) | Comstants used throughout KIMMDY |
| [coordinates](coordinates.qmd#kimmdy.coordinates) | TODO: WIP |
| [kmc](kmc.qmd#kimmdy.kmc) | Kinetic Monte Carlo (KMC) classes and functions. |
| [misc_helper](misc_helper.qmd#kimmdy.misc_helper) | Miscelaneous utilitiies that didn't fit anywhere else for now. |
| [parsing](parsing.qmd#kimmdy.parsing) | All read_<...> and write_<...> functions. |
| [runmanager](runmanager.qmd#kimmdy.runmanager) | The Runmanager is the main entry point of the program. |
| [tasks](tasks.qmd#kimmdy.tasks) |  |
| [utils](utils.qmd#kimmdy.utils) |  |
| [topology.topology.Topology](topology.topology.Topology.qmd#kimmdy.topology.topology.Topology) | Smart container for parsed topology data. |
| [topology.ff](topology.ff.qmd#kimmdy.topology.ff) |  |
| [topology.utils](topology.utils.qmd#kimmdy.topology.utils) |  |

## Other classes

TODO

| | |
| --- | --- |
| [runmanager.RunManager](runmanager.RunManager.qmd#kimmdy.runmanager.RunManager) | The Runmanager is the main entry point of the program. |

## Topology

Topology classes

| | |
| --- | --- |
| [topology.topology.Topology](topology.topology.Topology.qmd#kimmdy.topology.topology.Topology) | Smart container for parsed topology data. |
| [topology.ff](topology.ff.qmd#kimmdy.topology.ff) |  |
| [topology.utils](topology.utils.qmd#kimmdy.topology.utils) |  |

## Atomic types

Internal representations of topology and forcfield entities

| | |
| --- | --- |
| [topology.atomic](topology.atomic.qmd#kimmdy.topology.atomic) | Atomic datatypes for the topology such as Atom, Bond, Angle, Dihedral, etc. |
| [topology.atomic.Atom](topology.atomic.Atom.qmd#kimmdy.topology.atomic.Atom) | Information about one atom |
| [topology.atomic.AtomType](topology.atomic.AtomType.qmd#kimmdy.topology.atomic.AtomType) | Information about one atom |
| [topology.atomic.Bond](topology.atomic.Bond.qmd#kimmdy.topology.atomic.Bond) | Information about one bond |
| [topology.atomic.BondType](topology.atomic.BondType.qmd#kimmdy.topology.atomic.BondType) | Information about one bondtype |
| [topology.atomic.PositionRestraint](topology.atomic.PositionRestraint.qmd#kimmdy.topology.atomic.PositionRestraint) | Information about one position restraint. |
| [topology.atomic.DihedralRestraint](topology.atomic.DihedralRestraint.qmd#kimmdy.topology.atomic.DihedralRestraint) | Information about one dihedral restraint. |
| [topology.atomic.Pair](topology.atomic.Pair.qmd#kimmdy.topology.atomic.Pair) | Information about one pair |
| [topology.atomic.Angle](topology.atomic.Angle.qmd#kimmdy.topology.atomic.Angle) | Information about one angle |
| [topology.atomic.AngleType](topology.atomic.AngleType.qmd#kimmdy.topology.atomic.AngleType) | Information about one angle |
| [topology.atomic.DihedralType](topology.atomic.DihedralType.qmd#kimmdy.topology.atomic.DihedralType) | Information about one dihedral |
| [topology.atomic.ResidueAtomSpec](topology.atomic.ResidueAtomSpec.qmd#kimmdy.topology.atomic.ResidueAtomSpec) | Information about one atom in a residue |
| [topology.atomic.ResidueBondSpec](topology.atomic.ResidueBondSpec.qmd#kimmdy.topology.atomic.ResidueBondSpec) | Information about one bond in a residue |
| [topology.atomic.ResidueImproperSpec](topology.atomic.ResidueImproperSpec.qmd#kimmdy.topology.atomic.ResidueImproperSpec) | Information about one imroper dihedral in a residue |
| [topology.atomic.ResidueProperSpec](topology.atomic.ResidueProperSpec.qmd#kimmdy.topology.atomic.ResidueProperSpec) | Information about one imroper dihedral in a residue |
| [topology.atomic.ResidueType](topology.atomic.ResidueType.qmd#kimmdy.topology.atomic.ResidueType) | Information about one residuetype from aminoacids.rtp |

## Reactions

Protocol to add a new reaction plugin to KIMMDY

| | |
| --- | --- |
| [reaction.ReactionPlugin](reaction.ReactionPlugin.qmd#kimmdy.reaction.ReactionPlugin) | Reaction base class |
| [reaction.RecipeStep](reaction.RecipeStep.qmd#kimmdy.reaction.RecipeStep) | Base class for all RecipeSteps. |
| [reaction.Break](reaction.Break.qmd#kimmdy.reaction.Break) | Change topology to break a bond |
| [reaction.Bind](reaction.Bind.qmd#kimmdy.reaction.Bind) | Change topology to form a bond |
| [reaction.Move](reaction.Move.qmd#kimmdy.reaction.Move) | Change topology and/or coordinates to move an atom. |
| [reaction.SingleOperation](reaction.SingleOperation.qmd#kimmdy.reaction.SingleOperation) |  |
| [reaction.Recipe](reaction.Recipe.qmd#kimmdy.reaction.Recipe) | A reaction path defined by one series of RecipeSteps. |
| [reaction.RecipeCollection](reaction.RecipeCollection.qmd#kimmdy.reaction.RecipeCollection) | A RecipeCollection encompasses a number of reaction paths. |

## Reaction Plugins

Reaction plugins bundled with KIMMDY

| | |
| --- | --- |
| [reactions.homolysis](reactions.homolysis.qmd#kimmdy.reactions.homolysis) |  |