# kmc { #kimmdy.kmc }

`kmc`

Kinetic Monte Carlo (KMC) classes and functions.

In our system, the reaction rate r = (deterministic) reaction constant k
= stochastic reaction constant c (from gillespie 1977)
= propensity a (from Anderson 2007)
because of the fundamental premise of chemical kinetics
and because we have one reactant molecule

## Functions

| Name | Description |
| --- | --- |
| [frm](#kimmdy.kmc.frm) | First Reaction Method variant of Kinetic Monte Carlo. |
| [rf_kmc](#kimmdy.kmc.rf_kmc) | Rejection-Free Monte Carlo. |

### frm { #kimmdy.kmc.frm }

`kmc.frm(recipe_collection, rng=default_rng(), MD_time=None)`

First Reaction Method variant of Kinetic Monte Carlo.
takes RecipeCollection and choses a recipe based on which reaction would occur.

Compare e.g. <https://en.wikipedia.org/wiki/Kinetic_Monte_Carlo#Time-dependent_Algorithms>

#### Parameters

| Name                | Type                        | Description                                                                        | Default         |
|---------------------|-----------------------------|------------------------------------------------------------------------------------|-----------------|
| `recipe_collection` | RecipeCollection            | from which one will be choosen                                                     | _required_      |
| `rng`               | numpy.random.BitGenerator   | to generate random numbers in the KMC step                                         | `default_rng()` |
| `MD_time`           | typing.Union\[float, None\] | time [ps] to compare conformational events with reaction events in the time domain | `None`          |

### rf_kmc { #kimmdy.kmc.rf_kmc }

`kmc.rf_kmc(recipe_collection, rng=default_rng())`

Rejection-Free Monte Carlo.
takes RecipeCollection and choses a recipe based on the relative propensity of the events.


Compare e.g. <https://en.wikipedia.org/wiki/Kinetic_Monte_Carlo#Rejection-free_KMC>

#### Parameters

| Name                | Type                      | Description                                         | Default         |
|---------------------|---------------------------|-----------------------------------------------------|-----------------|
| `recipe_collection` | RecipeCollection          | from which one will be choosen                      | _required_      |
| `rng`               | numpy.random.BitGenerator | function to generate random numbers in the KMC step | `default_rng()` |