# reaction.RecipeCollection { #kimmdy.reaction.RecipeCollection }

`reaction.RecipeCollection(recipes)`

A RecipeCollection encompasses a number of reaction paths.
They can originate from multiple reaction plugins, but do not need to.

## Methods

| Name | Description |
| --- | --- |
| [aggregate_reactions](#kimmdy.reaction.RecipeCollection.aggregate_reactions) | Combines reactions having the same sequence of RecipeSteps. |
| [from_dill](#kimmdy.reaction.RecipeCollection.from_dill) |  |
| [to_csv](#kimmdy.reaction.RecipeCollection.to_csv) | Write a ReactionResult as defined in the reaction module to a csv file |
| [to_dill](#kimmdy.reaction.RecipeCollection.to_dill) |  |

### aggregate_reactions { #kimmdy.reaction.RecipeCollection.aggregate_reactions }

`reaction.RecipeCollection.aggregate_reactions(self)`

Combines reactions having the same sequence of RecipeSteps.

### from_dill { #kimmdy.reaction.RecipeCollection.from_dill }

`reaction.RecipeCollection.from_dill(cls, path)`

### to_csv { #kimmdy.reaction.RecipeCollection.to_csv }

`reaction.RecipeCollection.to_csv(self, path)`

Write a ReactionResult as defined in the reaction module to a csv file

### to_dill { #kimmdy.reaction.RecipeCollection.to_dill }

`reaction.RecipeCollection.to_dill(self, path)`