# runmanager.RunManager { #kimmdy.runmanager.RunManager }

`runmanager.RunManager(self, config)`

The Runmanager is the main entry point of the program.

Manages the queue of tasks, communicates with the
rest of the program and keeps track of global state.

## Attributes

| Name              | Type                                        | Description                                               |
|-------------------|---------------------------------------------|-----------------------------------------------------------|
| config            | Config                                      | The configuration object.                                 |
| from_checkpoint   | bool                                        | Whether the runmanager was initialized from a checkpoint. |
| tasks             | queue.Queue\[kimmdy.tasks.Task\]            | Tasks from config.                                        |
| crr_tasks         | queue.Queue\[kimmdy.tasks.Task\]            | Current tasks.                                            |
| iteration         | int                                         | Current iteration.                                        |
| iterations        | int                                         | Total number of iterations.                               |
| state             | State                                       | Current state of the system.                              |
| recipe_collection | RecipeCollection                            | Collection of recipes.                                    |
| latest_files      | dict\[str, pathlib.Path\]                   | Dictionary of latest files.                               |
| histfile          | Path                                        | Path to history file.                                     |
| cptfile           | Path                                        | Path to checkpoint file.                                  |
| ffpatch           |                                             | Path to force field patch file.                           |
| top               |                                             | Topology object.                                          |
| filehist          | list\[dict\[str, kimmdy.tasks.TaskFiles\]\] | List of dictionaries of TaskFiles.                        |
| task_mapping      | TaskMapping                                 | Mapping of task names to runmanager methods.              |

## Methods

| Name | Description |
| --- | --- |
| [get_latest](#kimmdy.runmanager.RunManager.get_latest) | Returns path to latest file of given type. |
| [run](#kimmdy.runmanager.RunManager.run) |  |

### get_latest { #kimmdy.runmanager.RunManager.get_latest }

`runmanager.RunManager.get_latest(self, suffix)`

Returns path to latest file of given type.

For .dat files (in general ambiguous extensions) use full file name.
Errors if file is not found.

### run { #kimmdy.runmanager.RunManager.run }

`runmanager.RunManager.run(self)`