# topology.topology.Topology { #kimmdy.topology.topology.Topology }

`topology.topology.Topology(self, top, ffpatch=None)`

Smart container for parsed topology data.

A topology keeps track of connections and applies patches to parameters when bonds are broken or formed.
Assumptions:
- the topology of interest (the protein) is in section 'moleculetype_0'.

## Parameters

| Name      | Type                            | Description                                                        | Default    |
|-----------|---------------------------------|--------------------------------------------------------------------|------------|
| `top`     | TopologyDict                    | A dictionary containing the parsed topology data.                  | _required_ |
| `ffpatch` | typing.Optional\[pathlib.Path\] | Path to a force field patch file. If None, no patching is applied. | `None`     |

## Methods

| Name | Description |
| --- | --- |
| [bind_bond](#kimmdy.topology.topology.Topology.bind_bond) | Add a bond in topology. |
| [break_bond](#kimmdy.topology.topology.Topology.break_bond) | Break bonds in topology. |
| [move_hydrogen](#kimmdy.topology.topology.Topology.move_hydrogen) | Move a singly bound atom to a new location. |
| [patch_parameters](#kimmdy.topology.topology.Topology.patch_parameters) |  |
| [reindex_atomnrs](#kimmdy.topology.topology.Topology.reindex_atomnrs) | Reindex atom numbers in topology. |
| [to_dict](#kimmdy.topology.topology.Topology.to_dict) |  |

### bind_bond { #kimmdy.topology.topology.Topology.bind_bond }

`topology.topology.Topology.bind_bond(self, atompair_nrs)`

Add a bond in topology.

Modifies the topology dictionary in place.
It keeps track of affected terms in the topology via a graph representation of the topology
and applies the necessary changes to bonds, angles and dihedrals (proper and improper).
Furthermore, it modifies to function types in the topology to account for radicals.

#### Parameters

| Name           | Type              | Description                                                                                                                                            | Default    |
|----------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `atompair_nrs` | tuple\[str, str\] | A tuple of integers with the atoms ids (id, starting at 1) with `from`, the atom being moved and `to`, the atom to which the `from` atom will be bound | _required_ |

### break_bond { #kimmdy.topology.topology.Topology.break_bond }

`topology.topology.Topology.break_bond(self, atompair_nrs)`

Break bonds in topology.

removes bond, angles and dihedrals where atompair was involved.
Modifies the topology dictionary in place.

### move_hydrogen { #kimmdy.topology.topology.Topology.move_hydrogen }

`topology.topology.Topology.move_hydrogen(self, from_to)`

Move a singly bound atom to a new location.

This is typically H for Hydrogen Atom Transfer (HAT).

### patch_parameters { #kimmdy.topology.topology.Topology.patch_parameters }

`topology.topology.Topology.patch_parameters(self, focus_nr)`

### reindex_atomnrs { #kimmdy.topology.topology.Topology.reindex_atomnrs }

`topology.topology.Topology.reindex_atomnrs(self)`

Reindex atom numbers in topology.

Starts at index 1.
This also updates the numbers for bonds, angles, dihedrals and pairs.

### to_dict { #kimmdy.topology.topology.Topology.to_dict }

`topology.topology.Topology.to_dict(self)`