name: build_examples

on:
  pull_request:
    branches: [main]
    types: [labeled]

permissions:
  contents: write

jobs:
  build-examples:
    if: github.event.label.name == 'build_examples'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          uv sync
      - name: Build docs
        run: |
          uv run kimmdy-build-examples -r hard
      - name: Commit rendered examples
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): rebuild examples"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          file_pattern: "example/"
          push_options: "--force"
