name: lint
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    if: "!startsWith(github.head_ref, 'release-please-')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
