name: test PR
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [labeled]

jobs:
  test:
    if:  github.event.label.name == 'testthis' && !startsWith(github.head_ref, 'release-please-')
    runs-on: ubuntu-latest
    container: riedmiki/gromacs-plumed-python:2021
    steps:
      - uses: actions/checkout@v3
      - name: run tox
        run: tox
      - name: zip coverage report
        if: ${{ !cancelled() }}
        run: zip -r htmlcov.zip htmlcov || true
      - uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: coverage artifact
          path: htmlcov.zip

          
